### ISSUE TITLE
Does not install on .NET 4.5.1 

### ISSUE THREAD

**Issue by ArsalanDotMe** [firebase/firebase-token-generator-dotNet#1]
The library does not install on Windows 8.1 Windows Store Apps due to compatibility issues with framework 4.5.1.

**Comment by Sun3** [comment]
Is there any plans for a Firebase C# SDK?

**Comment by jaguarsy** [comment]
@Sun3 you can see the [FireSharp](https://github.com/ziyasal/FireSharp) by ziyasal

**Comment by Sun3** [comment]
Yes, I have tried but unfortunately it crashes with Windows 10 Universal App c#.

**Comment by mikelehen** [comment]
There are definitely plans for a C# SDK, but no set timeline for it.  Sorry.  In the meantime, FireSharp is just a wrapper around our REST API (https://www.firebase.com/docs/rest/api/).  You should be able to basically copy what it's doing, if it's not working for you.

**Comment by Sun3** [comment]
@mikelehen Thanks I am working and still testing with FireSharp. By the way I am assuming that that REST API does not handle the offline sync features?

**Comment by mikelehen** [comment]
@Sun3 No, you would need to persist your changes locally and then re-send them when you come back online.  Sorry!
